const SET_GAME_STATUS = "SET_GAME_STATUS";
const SET_GAME_SCORE = "SET_GAME_SCORE";
const GET_QUESTION_LIST = "GET_QUESTION_LIST";

module.exports = { SET_GAME_STATUS, SET_GAME_SCORE, GET_QUESTION_LIST };
